"""Markdown report formatter for GitHub-friendly output."""

from __future__ import annotations

from typing import TYPE_CHECKING

from cow_performance.reporting.models import (
    ExecutiveSummary,
    PerformanceReport,
    Recommendation,
    RecommendationSeverity,
    ReportVerdict,
)
from cow_performance.reporting.summary import (
    format_duration,
    format_latency,
    format_rate,
)

if TYPE_CHECKING:
    from cow_performance.baselines.models import PerformanceBaseline
    from cow_performance.comparison.models import ComparisonResult


class MarkdownReportFormatter:
    """
    Formats performance reports as Markdown.

    Designed for GitHub PRs and documentation.
    """

    def format(self, report: PerformanceReport) -> str:
        """
        Format a complete performance report as Markdown.

        Args:
            report: The report to format

        Returns:
            Markdown formatted string
        """
        lines: list[str] = []

        # Header with verdict badge
        verdict_emoji = self._verdict_emoji(report.summary.verdict if report.summary else None)
        lines.append(f"# {verdict_emoji} Performance Report")
        lines.append("")

        # Metadata table
        lines.append("| Property | Value |")
        lines.append("|----------|-------|")
        lines.append(f"| Generated | {report.generated_at.strftime('%Y-%m-%d %H:%M:%S')} |")
        lines.append(f"| Report ID | `{report.report_id}` |")
        if report.git_commit:
            lines.append(
                f"| Git | `{report.git_branch or 'detached'}@" f"{report.git_commit[:8]}` |"
            )
        if report.scenario_name:
            lines.append(f"| Scenario | `{report.scenario_name}` |")
        lines.append("")

        # Executive Summary
        if report.summary:
            lines.extend(self._format_summary(report.summary))
            lines.append("")

        # Detailed Metrics
        if report.baseline:
            lines.extend(self._format_metrics(report.baseline))
            lines.append("")

        # Comparison Results
        if report.comparison:
            lines.extend(self._format_comparison(report.comparison))
            lines.append("")

        # Recommendations
        if report.recommendations:
            lines.extend(self._format_recommendations(report.recommendations))
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Generated by CoW Performance Testing Suite*")

        return "\n".join(lines)

    def _verdict_emoji(self, verdict: ReportVerdict | None) -> str:
        """Get emoji for verdict."""
        if verdict is None:
            return "📊"
        mapping = {
            ReportVerdict.SUCCESS: "✅",
            ReportVerdict.WARNING: "⚠️",
            ReportVerdict.FAILURE: "❌",
        }
        return mapping.get(verdict, "📊")

    def _severity_emoji(self, severity: RecommendationSeverity) -> str:
        """Get emoji for severity."""
        mapping = {
            RecommendationSeverity.CRITICAL: "🔴",
            RecommendationSeverity.WARNING: "🟠",
            RecommendationSeverity.INFO: "🔵",
        }
        return mapping.get(severity, "⚪")

    def _format_summary(self, summary: ExecutiveSummary) -> list[str]:
        """Format executive summary as Markdown."""
        lines = ["## Executive Summary", ""]

        # Verdict badge
        verdict_badge = self._verdict_emoji(summary.verdict)
        lines.append(f"**Verdict:** {verdict_badge} **{summary.verdict.value.upper()}**")
        lines.append(f"> {summary.verdict_reason}")
        lines.append("")

        # Test info
        lines.append(f"**Test:** {summary.test_name}")
        lines.append(f"**Duration:** {format_duration(summary.test_duration_seconds)}")
        lines.append("")

        # Metrics summary table
        lines.append("### Key Metrics")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Orders Submitted | {summary.total_orders_submitted:,} |")
        lines.append(f"| Orders Filled | {summary.total_orders_filled:,} |")
        lines.append(f"| Success Rate | {format_rate(summary.success_rate)} |")
        lines.append(f"| Avg Throughput | {summary.average_throughput:.2f} orders/sec |")
        lines.append(f"| Fill Latency (P95) | {format_latency(summary.fill_latency_p95_ms)} |")
        lines.append(f"| API Success Rate | {format_rate(summary.api_success_rate)} |")
        lines.append("")

        # Key findings
        if summary.key_findings:
            lines.append("### Key Findings")
            lines.append("")
            for finding in summary.key_findings:
                lines.append(f"- {finding}")
            lines.append("")

        return lines

    def _format_metrics(self, baseline: PerformanceBaseline) -> list[str]:
        """Format detailed metrics as Markdown."""
        lines = ["## Detailed Metrics", ""]

        # Order latencies table
        if baseline.order_metrics:
            om = baseline.order_metrics
            lines.append("### Order Lifecycle Latencies")
            lines.append("")
            lines.append("| Stage | P50 | P90 | P95 | P99 |")
            lines.append("|-------|-----|-----|-----|-----|")

            for name, stats in [
                ("Submit", om.time_to_submit),
                ("Accept", om.time_to_accept),
                ("Fill", om.time_to_fill),
                ("Total", om.total_lifecycle),
            ]:
                if stats.count > 0:
                    lines.append(
                        f"| {name} | "
                        f"{format_latency(stats.p50 * 1000)} | "
                        f"{format_latency(stats.p90 * 1000)} | "
                        f"{format_latency(stats.p95 * 1000)} | "
                        f"{format_latency(stats.p99 * 1000)} |"
                    )
            lines.append("")

        # Resource metrics
        if baseline.resource_metrics:
            lines.append("### Resource Utilization")
            lines.append("")
            lines.append("| Container | CPU (P95) | Memory (P95) |")
            lines.append("|-----------|-----------|--------------|")

            for name, metrics in baseline.resource_metrics.items():
                lines.append(
                    f"| {name} | {metrics.cpu_percent.p95:.1f}% | "
                    f"{metrics.memory_percent.p95:.1f}% |"
                )
            lines.append("")

        return lines

    def _format_comparison(self, comparison: ComparisonResult) -> list[str]:
        """Format comparison results as Markdown."""
        lines = ["## Comparison Results", ""]

        lines.append(f"**Baseline:** `{comparison.baseline_name}`")
        lines.append(f"**Current:** `{comparison.current_name}`")
        lines.append(f"**Verdict:** {comparison.verdict.value.upper()}")
        lines.append("")

        # Regressions table
        if comparison.regressions:
            lines.append("### Regressions")
            lines.append("")
            lines.append("| Severity | Metric | Change |")
            lines.append("|----------|--------|--------|")
            for reg in comparison.regressions:
                severity = f"{reg.regression_severity.value}"
                change = f"{reg.percent_change * 100:+.1f}%"
                lines.append(f"| {severity} | `{reg.metric_name}` | {change} |")
            lines.append("")

        # Improvements table
        if comparison.improvements:
            lines.append("### Improvements")
            lines.append("")
            lines.append("| Metric | Change |")
            lines.append("|--------|--------|")
            for imp in comparison.improvements:
                change = f"{imp.percent_change * 100:+.1f}%"
                lines.append(f"| `{imp.metric_name}` | {change} |")
            lines.append("")

        return lines

    def _format_recommendations(self, recommendations: list[Recommendation]) -> list[str]:
        """Format recommendations as Markdown."""
        lines = ["## Recommendations", ""]

        for rec in recommendations:
            emoji = self._severity_emoji(rec.severity)
            lines.append(f"### {emoji} {rec.title}")
            lines.append("")
            lines.append(f"**Category:** {rec.category.value}")
            lines.append("")
            lines.append(rec.description)
            lines.append("")
            lines.append(f"**Action:** {rec.action}")
            lines.append("")

        return lines
